<rss version="2.0">
    <channel>
        <title><?=$this->category->title;?></title>
        <description><?=$this->category->description;?></description>
        <language>en-Us</language>
        <pubDate></pubDate>
        <?php foreach ($this->posts as $post):?>
         <item>
            <title><?=$post->title;?></title>
            <link><?=$post->link;?></link>
            <description><?=$post->description;?></description>
            <pubDate><?=$this->date($post->publishDate);?></pubDate>
         </item>
        <?php endforeach;?>
    </channel>
</rss>