<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<opml version="1.1">
    <head>
        <title><?=$this->category->title;?></title>
        <ownerName>IFPHP</ownerName>
        <ownerEmail>support@ifphp.com</ownerEmail>
    </head>
    <body>
        <?php foreach ($this->category->feeds as $feed):?>
            <outline text="<?=$feed->title;?>" count="" xmlUrl="<?=$feed->url;?>" htmlUrl="<?=$feed->siteUrl;?>" />
        <?php endforeach; ?>
    </body>
</opml>