<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
 <li class="previous">
  <a href="<?= $this->url(array('page' => $this->previous)); ?>">
     <img src="<?=$this->baseUrl();?>/imgs/layout/global/pagination_left.gif" alt="ifphp" />
  </a>
 </li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
    <a href="<?=$this->url(array('page' => $page)); ?>">
        <?=$page; ?>
    </a>
   </li>
  <?php else: ?>
     <li class="active"><?=$page; ?></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li class="next">
  <a href="<?=$this->url(array('page' => $this->next)); ?>">
     <img src="<?=$this->baseUrl();?>/imgs/layout/global/pagination_right.gif" alt="ifphp" />
  </a>
</li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>