<?php $this->headTitle( $this->translate('About')); ?>
<h3><?= $this->translate('About')?></h3>
 
<div class="hr dotted"><hr /></div>

<div class="content-body">

<style>
    .team-member-left{
        float:left;
        margin-right:20px;
        margin-top:20px;
        margin-bottom:20px;
        width:150px;    
    }
    .team-member-right{
        float:left;
        margin-left:90px;
        margin-right:20px;
        margin-top:20px;
        margin-bottom:20px;
        width:150px;    
    }
</style>

<p>Here's the Ifphp Development Team!
</p>
<div class="team-member-left">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/akeem-philert.jpg"/>
    </div>
    <div >
        <p>
        Akeem Philbert<br />
        New York, NY
        </p>
    </div>
</div>

<div class="team-member-right">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/albert-rosa.jpg"/>
    </div>
    <div >
        <p>
        Albert Rosa<br />
        New York, NY
    </p>
    </div>
</div>

<div class="team-member-left">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/andy-prondack.jpg"/>
    </div>
    <div>
        <p>
        Andy Prondack<br />
        New York, NY
       </p>
    </div>
</div>

<div class="team-member-right">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/john-gist.jpg"/>
    </div>
    <div >
        <p>
        John Gist<br />
        New York, NY
    </p>
    </div>
</div>

</div>    
