<?php $this->headTitle( $this->translate('About')); ?>
<h3><?= $this->translate('About')?></h3>
 
<div class="hr dotted"><hr /></div>

<div class="content-body">

<style>
    .team-member-left{
        float:left;
        margin-right:20px;
        margin-top:20px;
        margin-bottom:20px;
        width:150px;    
    }
    .team-member-right{
        float:left;
        margin-left:90px;
        margin-right:20px;
        margin-top:20px;
        margin-bottom:20px;
        width:150px;    
    }
</style>

    <p>IFPHP is a feed/news aggregator built specifically for PHP news. Inspired by Adobe&trade; Feeds, IFPHP aims to be a resource for users to stay in touch with what others are doing in the PHP community by making it easy to contribute and consume news feed. The project was started by a core team of developers but we invite anyone to contribute by <a href="http://github.com/akeemphilbert/ifphp/tree/master">participating in development</a>, reporting issues in the <a href="http://github.com/akeemphilbert/ifphp/issues" target="_blank">issue tracker</a>, participating in our <a href="http://groups.google.com/group/ifphp" target="_blank">google group</a> or simply <a href="/feed/submit/">submit</a> a feed. Here's the Ifphp Development Team!</p>
<div class="team-member-left">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/akeem-philbert.jpg"/>
    </div>
    <div >
        <p>
            <a href="http://ak33m.com">Akeem Philbert</a><br />
        New York, NY
        </p>
    </div>
</div>

<div class="team-member-right">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/albert-rosa.jpg"/>
    </div>
    <div >
        <p>
            <a href="http://albertrosa.com">Albert Rosa</a><br />
        New York, NY
    </p>
    </div>
</div>

<div class="team-member-left">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/andy-prondak.jpg"/>
    </div>
    <div>
        <p>
            <a href="http://igeekout.com">Andy Prondack</a><br />
        New York, NY
       </p>
    </div>
</div>

<div class="team-member-right">
    <div style="margin-bottom: 5px;"> 
        <img src="<?= $this->baseUrl()?>/imgs/about/john-gist.jpg"/>
    </div>
    <div >
        <p>
            <a href="http://johnnyjuice.com/">John Gist</a><br />
        New York, NY
    </p>
    </div>
</div>

</div>    
