  <h3>Most Recent</h3>
    <div class="rss">
    	<a href="<?=$this->baseUrl(); ?>/?format=rss" title="">RSS</a>
	</div>
        <div class="hr dotted"><hr /></div>
        <div class="utilities">
        <!--PAGINATION-->      
         <?= $this->paginationControl($this->paginator, 'Sliding', '/partials/paginator/list.phtml'); ?>  
              <?= $this->paginator?>
        <!--END PAGINATION-->
        <!--TRANSLATION SELECTOR-->
        <div class="translation-selector">
            <select name="translate">
                <option selected="selected">Translate</option>
                <option>English</option>
            </select>
		</div>
        <!-- END TRANSLATION SELECTOR-->
   		</div>


<?php foreach ($this->posts as $post):?>
	<?=$this->partial('partials/post.phtml',array('post'=>$post));?>
<?php endforeach;?>
<?= $this->paginator;?>

