<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<rss version="2.0">
    <channel>
        <title>IFPHP Recent Posts Feed</title>
        <description>Recently aggregated posts</description>
        <language>en-Us</language>
        <pubDate></pubDate>
        <?php foreach ($this->posts as $post):?>
         <item>
            <title><?=$post->title;?></title>
            <link><?=$post->link;?></link>
            <description><![CDATA[<?=$post->description;?>]]></description>
            <pubDate><?=$this->date($post->publishDate);?></pubDate>
         </item>
        <?php endforeach;?>
    </channel>
</rss>