<?php $this->headMeta()->appendName('keywords','php,news aggregator,feed'); ?>
<?php $this->headMeta()->appendName('description','IFPHP is a news/blog feed aggregator for the PHP community. Anyone can submit and consume PHP related news feeds'); ?>
<h3>Most Recent</h3>
    <div class="rss">
    	<a href="<?=$this->baseUrl(); ?>/?format=rss" title="">RSS</a>
	</div>
        <div class="hr dotted"><hr /></div>    
        <?= $this->paginator?>
<?php foreach ($this->posts as $post):?>
        <?php if($this->posts->key() != 0):?>
        <div class="hr simple"><hr /></div>
        <?php endif;?>
	<?=$this->partial('partials/post.phtml',array('post'=>$post));?>
<?php endforeach;?>
<div class="utilities">
</div>


<div id="posts-footer" class="utilities">
       <?= $this->paginator?>
</div>
