<?php $this->headTitle($this->translate('Support')); ?>
<h3><?= $this->translate('Support')?></h3> 
<div class="hr dotted"><hr /></div>
<?php if($this->supports):?>
	<p>Support for : <?= $this->term?></p>
	<ul>
		<?php foreach($this->supports as $support):?>
		<li><span class="bold"><?= $support->title?></span>:<br/>
			<?= $support->content?>
		</li>
		<?php endforeach;?>
	</ul>
<?php else:?>

<?php endif;?>