
<div class="footer last">
	<div class="footer-content">
  	<ul>
    	<li class=""><a class="" href="<?= $this->baseUrl()?>/"><?= $this->translate('Home')?></a></li>
      	<li class=""><a class="" href="<?= $this->baseUrl()?>/feed/submit/"><?= $this->translate('Submit Feed')?></a></li>
      	<li class=""><a class="" href="<?= $this->baseUrl()?>/feed/ping/"><?= $this->translate('Ping Feed')?></a></li>
      	<li class=""><a class="" href="<?= $this->baseUrl()?>/weblogs"><?= $this->translate('Weblogs')?></a></li>
      	<li class=""><a class="" href="<?= $this->baseUrl()?>/support"><?= $this->translate('Support')?></a></li>
      	<li class=""><a class="" href="<?= $this->baseUrl()?>/about/"><?= $this->translate('About')?></a></li>
	</ul>
    <ul class="copyright">
    	<li>&copy;Copyright 2009</li>
    </ul>
	</div>
  </div>
