  <div class="navigation">
    <ul>
      <li class="home"><a class="" href="<?= $this->baseUrl()?>/"><?= $this->translate('Home')?></a></li>
      <li class="submit-feed"><a class="" href="<?= $this->baseUrl()?>/feed/submit/"><?= $this->translate('Submit Feed')?></a></li>
      <li class="ping-feeds"><a class="" href="<?= $this->baseUrl()?>/feed/ping/"><?= $this->translate('Ping Feed')?></a></li>
      <li class="blogs"><a class="" href="<?= $this->baseUrl()?>/weblogs"><?= $this->translate('Weblogs')?></a></li>
      <li class="support"><a class="" href="<?= $this->baseUrl()?>/support"><?= $this->translate('Support')?></a></li>
      <li class="about last"><a class="" href="<?= $this->baseUrl()?>/about/"><?= $this->translate('About')?></a></li>
    </ul>
  </div>