  <div class="navigation">
    <ul>
      <li><a href="<?= $this->baseUrl()?>">Home</a></li>
      <li><a href="<?= $this->baseUrl()?>/feed/submit/">Submit Feed</a></li>
      <li><a href="<?= $this->baseUrl()?>/feed/ping/">Ping Feeds</a></li>
      <li><a href="<?= $this->baseUrl()?>/weblogs">Weblogs</a></li>
      <li class="last"><a href="<?= $this->baseUrl()?>/about/">About</a></li>
      <li><a href="<?= $this->baseUrl()?>/support">Support</a></li>
    </ul>
  </div>