<h3><?= $this->translate('Weblogs');?></h3>
<div class="hr dotted"><hr /></div>
<table>
	<thead>
		<tr><th>Category</th><th>OPML</th></tr>
	</thead>
	<tbody>
		<?php foreach($this->categories as $cat):?>
	
		<tr>
			<td><?= $cat->title?></td>
			<td>
				<select id="feedByCategory" name="feedByCategory">
					<?php foreach($this->feedsByCategory[$cat->title] as $feed):?>
						<option value='<?= $feed->id?>'>
							<?= $feed->title ?>
						</option>
					<?php endforeach;?>
				</select>
			</td>
		</tr>		
		<?php endforeach;?>	
	</tbody>
</table>


<table>

	<caption>All Feeds</caption>
	<thead>
	<tr>
		<th>Name</th>
		<th>Site</th>
		<th>Language</th>
		<th>Last Updated</th>
	</tr>
	</thead>
	<tbody>
		<?php foreach ($this->feeds as $feed):?>
			<tr>
				<th><?= $feed->title?></th>
				<th><?= $feed->siteUrl?></th>
				<th><?= $feed->language?></th>
				<th><?= $this->date($feed->modified)?></th>
			</tr>
		<?php endforeach;?>
		
	</tbody>

</table>