<h3><?=$this->translate('Weblogs');?></h3>
<div class="hr dotted"><hr /></div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin interdum purus hendrerit magna malesuada non volutpat urna lobortis. Suspendisse potenti. Sed lacus nisi, interdum quis porta non, dapibus in urna. Integer arcu eros, euismod non ornare ultrices, congue in metus.</p>

<table>
	<thead>
		<tr><th>Category</th><th>OPML</th></tr>
	</thead>
	<tbody>
		<?php foreach($this->categories as $category):?>

		<tr>
			<td><?= $category->title?></td>
			<td>
                            <div class="opml">
                                <a href="<?=$this->baseUrl();?>/category/view/<?=$category->slug;?>/?format=opml" title="">OPML</a>
                            </div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<?php foreach ($this->categories as $category):?>
<h4><?=$category->title;?></h4>
<div class="hr dotted"><hr /></div>

<table>

	<thead>
	<tr>
		<th>Name</th>
		<th>Site</th>
		<th>Language</th>
		<th>Last Updated</th>
	</tr>
	</thead>
	<tbody>
		<?php foreach ($category->feeds as $feed):?>
			<tr>
				<th><?= $feed->title?></th>
				<th><?= $feed->siteUrl?></th>
				<th><?= $feed->language?></th>
				<th><?= $this->date($feed->modified)?></th>
			</tr>
		<?php endforeach;?>

	</tbody>

</table>
<?php endforeach;?>