<?php foreach ($this->categories as $category):?>
<?php $tc[] = $category->title;?>
<?php endforeach;?>
<?php $this->headMeta()->appendName('keywords','php,feeds,framework,'.implode(',',$tc)); ?>
<?php $this->headMeta()->appendName('description','List of categories and feed. Categories include popular PHP frameworks and CMS'); ?>
<h3><?=$this->translate('Weblogs');?></h3>
<div class="hr dotted"><hr /></div>
<div class="content-body">
<p>Below is a list of categories as well as the list of feeds that are aggregated by category.</p>

<table>
	<thead>
		<tr><th>Category</th><th>OPML</th></tr>
	</thead>
	<tbody>
		<?php foreach($this->categories as $category):?>

		<tr>
			<td><a href="<?=$this->baseUrl('/category/view/'.$category->slug.'/');?>"><?= $category->title?></a></td>
			<td>
                            <div class="opml">
                                <a href="<?=$this->baseUrl();?>/category/view/<?=$category->slug;?>/?format=opml" title="">OPML</a>
                            </div>
			</td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<?= $this->headTitle($this->translate('Weblogs'));?>
<?php foreach ($this->categories as $category):?>
<h4><?=$category->title;?></h4>
<div class="hr dotted"><hr /></div>

<table>

	<thead>
	<tr>
		<th>Name</th>
                <th>Feed</th>
		<th>Site</th>
		<th>Last Updated</th>
	</tr>
	</thead>
	<tbody>
		<?php foreach ($category->feeds as $feed):?>
			<tr>
				<td><a href="<?=$this->baseUrl('/feed/view/'.$feed->slug);?>"><?= $feed->title?></a></td
                                <td><div class="rss">
                                <a href="<?=$feed->url;?>" title="">RSS</a>
                            </div></td>
				<td><a href="http://<?=$feed->siteUrl;?>"><?= $feed->siteUrl?></a></td>
				<td><?= $this->date($feed->modified)?></td>
			</tr>
		<?php endforeach;?>

	</tbody>

</table>
<?php endforeach;?>
</div>