<?php foreach ($this->messages as $message):?>
<div class="notice"><?=$message ?></div>
<?php endforeach;?>
<h3><?=$this->feed->title;?></h3>
<div class="rss">
    <a href="<?=$this->feed->url; ?>" title="">RSS</a>
</div>
<div class="hr dotted"><hr /></div>
<div class="utilities">
<!--PAGINATION-->
<?= $this->paginator?>
<!--END PAGINATION-->
<!--TRANSLATION SELECTOR-->
    <div class="translation-selector">
        <select name="translate">
            <option selected="selected">Translate</option>
            <option>English</option>
        </select>
    </div>
<!-- END TRANSLATION SELECTOR-->
</div>
<?php foreach ($this->posts as $post):?>
<?=$this->partial('partials/post.phtml',array('post'=>$post));?>
<?php endforeach;?>
<div id="posts-footer" class="utilities">
       <?= $this->paginator?>
</div>