<p>
    Thank you for submitting your feed to <a href="<?=$this->serverUrl().'/';?>">IFPHP</a>
</p>
<p>
    To get your feed populated on the website please click this activation link - <a href="<?=$this->serverUrl('/'.$this->activationLink);?>"><?=$this->serverUrl('/'.$this->activationLink);?></a>
</p>
<p>
    Want to let us know when you add posts to you website? Us this pingback link - <a href="<?=$this->serverUrl('/'.$this->pingbackLink);?>"><?=$this->serverUrl('/'.$this->pingbackLink); ?></a>
</p>
<p>
    Don't forget you can subscribe to category feeds or even create your own using search and plug it in to your favorite feed reader.
</p>
<p>
    IFPHP Team
</p>
