<div class="post clear">
    <p class="post-title"><a href="<?=$this->post->link;?>"><?=$this->post->title;?></a></p>
    
      <ul class="post-info">
          <li>
	    <span class="blog-name"><a href="<?=$this->baseUrl();?>/feed/view/<?=$this->post->feedSlug;?>/"><?=$this->post->feedTitle;?></a></span> - <span class="date"><?=$this->date($this->post->publishDate);?></span>
          </li>
        <!--<li>|</li>
        <li><a href="#" title="">Bookmark</a></li>
        <li>|</li>
        <li><a href="#" title="">Share</a></li>
        <li>|</li>        
        <li><select name="translate"><option selected="selected">Translate</option><option>English</option></select></li>
        -->
      </ul>
 	 <p><?=$this->post->description;?>...</p>
</div>