<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li class="previous">
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
     <img src="imgs/layout/global/pagination_left.gif" alt="ifphp" />
  </a>
</li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  <li>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a>
   </li>
  <?php else: ?>
    <li class="active"><?php echo $page; ?></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li class="next">
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
     <img src="imgs/layout/global/pagination_right.gif" alt="ifphp" />
  </a>
</li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>