 <div class="popular-blogs">
    <h4><?= $this->translate('Popular Blogs')?></h4>
        <ul>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
        </ul>
    </div>