  <div class="recently-updated-blogs">
    <h4>Recently Update Blogs</h4>
        <ul>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
        </ul>
    </div>