 <div class="smart-categories">
    <h4><?= $this->translate('Smart Categories')?></h4>
        <ul>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
        </ul>
    </div>