 <div class="smart-categories">
    <h4>Smart Categories</h4>
        <ul>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
            <li><a href="#">Lorem Ipsum Dolor</a></li>
        </ul>
    </div>