<?=$this->docType();?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php $this->headTitle()->setSeparator(' - ')?>
<?= $this->headTitle('IFPHP');?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<!-- Framework CSS -->
<?php $this->headLink()->prependStylesheet($this->baseUrl() .'/css/fancy-type/screen.css','screen, projection'); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl() .'/css/ie.css','screen, projection','lt IE 8'); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl() .'/css/print.css',	'print'); ?>
<?php $this->headLink()->prependStylesheet($this->baseUrl() .'/css/screen.css','screen, projection'); ?>
<?php $this->jQuery()->enable();?>
<?php $this->jQuery()->addJavascriptFile($this->baseUrl().'/js/global.js');?>
<?php $this->jQuery()->addOnLoad('Main.init();');?>

<!-- RSS FEED-->
<?php $this->headLink()->appendAlternate($this->baseUrl().'?format=rss', 'application/rss+xml', 'IFPHP RSS FEED'); ?>

<!-- META DATA -->
<?= $this->headMeta()?>
<?= $this->headLink() ?>
<?= $this->headScript() ?>
</head>  
<body>
<div class="container">
<div class="header">
  <h1><a href="/" title="IFPHP">ifphp</a></h1>
  <div class="search">
		<h2 class="alt"><?= $this->translate('PHP News Aggregator')?> | <?= $this->translate('Aggregating') ?> <?=$this->feedCount() ?> <?= $this->translate('feeds')?></h2>
      <div id="search_box">
        <?= $this->partial('/partials/html/search.phtml')?>        
      </div>
  </div>
  
  <?= $this->partial('/partials/html/navigation.phtml')?>
</div>
  <hr class="space" />
  <div class="content colborder">
<?= $this->layout()->content ?>
</div>
  <div class="sidebar">
    <?= $this->action('list','category') ?>
    <hr />    
    <?= $this->action('list','language') ?>
  	<div class="follow-us">
  		<a href="http://www.twitter.com/ifphp" title=""><img src="<?= $this->baseUrl()?>/imgs/layout/global/iphp_followus.png" alt="Follow ifphp on Twitter" /></a>
  	</div>
  </div>
  <div class="sidebar last">
    <?= $this->action('recently-updated','feed') ?>
    <hr />
    <?= $this->action('popular','feed') ?>    
  </div>        
</div>
<?= $this->partial('/partials/html/footer.phtml') ?>
<?= $this->jQuery(); ?>
    <script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-631170-6");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>